### ISSUE TITLE
github.io instead of sphinx for API3.geo.admin.ch

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3645] opened 2016-12-05 10:19 UTC
using github.io for documenting our api3.geo.admin.ch instead of sphinx

-> possible? makes sense?

**Comment by procrastinatio** [comment] 2016-12-07 16:18
For splitting the mamoth, yes.

github.io is markdown, sphinx is restructred text, but gateway do exists (not tested). 
Alternative, [read the docs](https://readthedocs.org/), standrd by python project

Also to consider, [swagger](http://swagger.wordnik.com/) and consort to describe ([slate](https://github.com/lord/slate), test and use API.

**Comment by hpchrist** [comment] 2016-12-16 16:57
you're not the first, see 

https://github.com/auth0/docs
https://www.terraform.io/docs/index.html

**Comment by boecklic** [comment] 2019-05-08 09:14
duplicate of https://github.com/geoadmin/mf-chsdi3/issues/3088

**Closed by boecklic** 2019-05-08 09:14 UTC
Labels: question
