### ISSUE TITLE
Exact result in SPHINX not shown "Dom"

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4287] opened 2018-04-23 15:45 UTC
Hi

the location "Dom" entered in swisssearch does not show up the peak "Dom " in the result

I assume it is due to the fact that the sphinx search needs more than 3 char otherwise it starts only with the guess

-> ideas?

Customer feedback ID : 2018042108134534

**Comment by oterral** [comment] 2018-04-24 11:27
When a query fit a complete word it should be on first place.

**Comment by AFoletti** [comment] 2018-05-04 08:49
we have some client reports about that issue too.
Try searching for "Ricken". There is an exact match but is buried after tons of other things.

**Comment by ltclm** [comment] 2018-06-19 05:32
duplicate of https://github.com/geoadmin/mf-chsdi3/issues/2925

**Comment by ltclm** [comment] 2019-01-14 14:36
there are other customer complaints concerning missing results with exact matches:
p.e. search for ``entle`` should return the river Entle but it does not.

https://api3.geo.admin.ch/rest/services/ech/SearchServer?sr=2056&searchText=entle&lang=de&type=locations&origins=gazetteer

**Comment by davidoesch** [comment] 2019-01-14 19:31
Any idea for a solution? sphinx community?

**Comment by ltclm** [comment] 2019-01-14 20:52
yes, i think it's worth a try to separate non-fuzzy queries into wildcard queries and exact match queries:
https://stackoverflow.com/questions/44883623/how-to-boost-relevance-for-exact-match-results-when-using-wildcard-in-sphinx

**Comment by davidoesch** [comment] 2019-01-14 20:57
I hope performance wise it works...

**Comment by ltclm** [comment] 2019-02-28 07:39
fix is online

**Closed by ltclm** 2019-02-28 07:39 UTC
Labels: 1st prio
