### ISSUE TITLE
[MVT] navigation behaviour outside Switzerland

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#4619] opened 2018-12-03 08:55 UTC
OS: Win10, desktop; Chrome
Steps to reproduce: 1.) open app, zoom out until you see a worldwide map, then try to zoom to Iceland 2.) enter 600000 200000 into the search field, try to zoom or pan in that area near Stockholm, Sweden
Result: 1.) application zooms back to Switzerland using the scrollwheel of the mouse. 2.) application "jumps" back to an extent in the area of Munich, Germany.
Expected: application zooms where user wants to go to.
Question: is this behaviour wanted?

**Comment by davidoesch** [comment] 2018-12-03 11:40
Duplicate of https://github.com/geoadmin/mf-geoadmin3/issues/4557

**Closed by davidoesch** 2018-12-03 11:40 UTC
Labels: question
