### ISSUE TITLE
[MVT] Enabling GPS Undefined

### ISSUE THREAD

**Issue by m-kuhn** [geoadmin/mf-geoadmin3#4922] opened 2019-05-05 13:37 UTC
When trying to enable the GPS on test.map.geo.admin.ch , a message box says "undefined". GPS on the device is turned on and working on the page map.geo.admin.ch .

![image](https://user-images.githubusercontent.com/588407/57194819-8a98a280-6f4b-11e9-83df-947cf51b2ff8.png)

**Comment by davidoesch** [comment] 2019-05-05 13:53
TBD is this is a wontfix during Testphase

**Comment by fredj** [comment] 2019-05-06 06:49
This one is probably caused by this change in OpenLayers: https://github.com/openlayers/openlayers/pull/8731

Quick (untested) fix:
```diff
diff --git a/src/components/geolocation/GeolocationDirective.js b/src/components/geolocation/GeolocationDirective.js
index 12c878b71..2b42fbacd 100644
--- a/src/components/geolocation/GeolocationDirective.js
+++ b/src/components/geolocation/GeolocationDirective.js
@@ -241,16 +241,16 @@ goog.require('ga_throttle_service');
           elts.removeClass(naClass);
           var msgId;
           switch (error.code) {
-            case error.PERMISSION_DENIED:
+            case 1:
               msgId = 'geoloc_permission_denied';
               break;
-            case error.POSITION_UNAVAILABLE:
+            case 2:
               msgId = 'geoloc_pos_unavailable';
               break;
-            case error.TIMEOUT:
+            case 3:
               msgId = 'geoloc_time_out';
               break;
-            case error.UNKNOWN_ERROR:
+            default:
               msgId = 'geoloc_unknown';
               break;
           }
```

Ref: https://developer.mozilla.org/en-US/docs/Web/API/PositionError

**Comment by pakb** [comment] 2019-05-06 10:08
working on a fix with @fredj's proposal here (thanks!) : https://github.com/geoadmin/mf-geoadmin3/pull/4923
Still need to fix our `flyTo` function that zooms where we are.

**Comment by pakb** [comment] 2019-05-13 06:13
Fix deployed on https://test.map.geo.admin.ch

**Closed by pakb** 2019-05-13 06:13 UTC
Labels: 3rd prio, MVT, bug
