### ISSUE TITLE
Style of "Positioninformationbox" differs

### ISSUE THREAD

**Issue by danielabrandt** [geoadmin/mf-geoadmin3#2514] opened 2015-07-23 07:22 UTC
Hi Style of Position Information box while klicking on this link with KML https://s.geo.admin.ch/65e52496fe  is different than the normal one (see screenshot)

![positioninformation](https://cloud.githubusercontent.com/assets/5592275/8845106/124c9546-311c-11e5-8a02-2acc318a0422.JPG)

**Comment by davidoesch** [comment] 2015-07-23 07:29
duplicate of 2015

**Comment by gjn** [comment] 2015-07-23 07:36
Can't reproduce this.

**Comment by gjn** [comment] 2015-07-23 07:38
Duplicate of #2515...now I can reproduce.

**Comment by oterral** [comment] 2015-07-23 07:40
Step to reproduce : 
1) Click on a marker --> that displays the tooltip
2) Right click on the map, the css appears like in the screenshot

The css of the contetn of tooltip breaks the css of the app.

@pauloamado can you fix the CSS of the KML description ?

**Closed** 2015-07-23 07:41 UTC
Labels: 2nd prio

**Comment by pauloamado** [comment] 2015-07-23 10:14
the CSS in KML description has been adapted. It works now.
