### ISSUE TITLE
Mouseclick sensitivity tooltip: very small

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2942] opened 2015-11-26 15:19 UTC
This is a reoccurring  issue for all tooltips
"Ich finde den sensiblen Bereich für den Klick auf ein Symbol (oranger Kreis) ein bisschen klein, vor allem wenn man weit hineingezoomt hat:"
![unbenannt](https://cloud.githubusercontent.com/assets/4577727/11425944/daad664c-9458-11e5-94e7-cb0b19caed4b.PNG)

Proposal

A) we really do increase once again the click perimeter

or

B) We extend the tooltip highlight / sensitivity from a circle to the icon size , or at least we define a paramtere for the sensitivity related to the mako template

or

C) we minimize the size of the icons smaller on large scale to fit the current extent of the tooltip circle /sensitivity

Decision:

"increase  the click perimeter"

- [ ] define ranges depending on zoom levels, 
- [ ] test them with a couple of typical layers
- ch.bazl.luftfahrthindernis
- ch.bafu.hydroweb-messstationen_gefahren
- ch.bfs.gebaeude_wohnungs_register
- ch.bav.haltestellen-oev
- [ ] decision on how to proceed (add an additional col in BOD? "wait" for vec tiles? etc)

**Comment by davidoesch** [comment] 2015-11-26 22:10
C) +1

**Comment by gjn** [comment] 2015-11-27 09:01
C) would require re-creating tiles for all affected layers...And the icons are IMO not too big.

There are 2 issues at play here.

1) We have a fixed tolerance in pixels for the underlying identify request. It's 5 pixels on desktop and 15 on mobile devices. This is clearly too small with high zoom levels. For points, the obvious solution would be to adapt the tolerance to the icon size. But we don't know icon sizes on pixel tiles. It's known during data creation. Maybe it's worth keeping track of those. This would be needed for B)

2) The actual request is not done on the icon/graphical representation, but on the underlying geometry.

I think a first approach would be A), generally increase to click tolerance. We can even define ranges depending on zoom levels, test them with a couple of typical layers and then decide. (Luftfahrthindernisse is a good example as well of this problematic).

Of course, vector layers (with vector tiles) would solve all of this...

**Comment by davidoesch** [comment] 2015-11-27 09:09
Decision:

"increase the click perimeter"

 define ranges depending on zoom levels,
 test them with a couple of typical layers
ch.bazl.luftfahrthindernis
ch.bafu.hydroweb-messstationen_gefahren
ch.bfs.gebaeude_wohnungs_register
ch.bav.haltestellen-oev decision on hwo to proceed (add an additional col in BOD? "wait" for vec tiles? etc)

**Comment by gjn** [comment] 2015-11-27 09:57
We'll push vector tiles. I wonder how the price-model for those will look like ;)

**Comment by loicgasser** [comment] 2015-12-01 08:45
+1 for A)

**Comment by gjn** [comment] 2015-12-01 13:28
Here are some testlinks with different pixel tolerances. Note: no zoom related logic applied for now. It's the same tolerance for every zoom level. It's for playing around and finding the good zoom/tolerance relation.

[Default tolerance (5px)](https://mf-geoadmin3.dev.bgdi.ch/gjn_tolerance/?lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,ch.bazl.luftfahrthindernis,ch.bav.haltestellen-oev&layers_visibility=false,true,false,false,true,true&layers_timestamp=18641231,,,,,&X=198415.36&Y=616169.07&zoom=2)
[10px Tolerance](https://mf-geoadmin3.dev.bgdi.ch/gjn_tolerance/?lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,ch.bazl.luftfahrthindernis,ch.bav.haltestellen-oev&layers_visibility=false,true,false,false,true,true&layers_timestamp=18641231,,,,,&X=198415.36&Y=616169.07&zoom=2&tolerance=10)
[15px Tolerance](https://mf-geoadmin3.dev.bgdi.ch/gjn_tolerance/?lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,ch.bazl.luftfahrthindernis,ch.bav.haltestellen-oev&layers_visibility=false,true,false,false,true,true&layers_timestamp=18641231,,,,,&X=198415.36&Y=616169.07&zoom=2&tolerance=15)
[20px Tolerance](https://mf-geoadmin3.dev.bgdi.ch/gjn_tolerance/?lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,ch.bazl.luftfahrthindernis,ch.bav.haltestellen-oev&layers_visibility=false,true,false,false,true,true&layers_timestamp=18641231,,,,,&X=198415.36&Y=616169.07&zoom=2&tolerance=20)
[30px Tolerance](https://mf-geoadmin3.dev.bgdi.ch/gjn_tolerance/?lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,ch.bazl.luftfahrthindernis,ch.bav.haltestellen-oev&layers_visibility=false,true,false,false,true,true&layers_timestamp=18641231,,,,,&X=198415.36&Y=616169.07&zoom=2&tolerance=30)

Note: we don't have problems with geojson layers like ch.bafu.hydroweb-messstationen_gefahren. It's a vector layer so we can detect exact geometry in client.

**Comment by davidoesch** [comment] 2015-12-01 14:04
Test on mobile- this is the limit

It is really tricky to find here the right dimension




The 30px is not enough eg for the best res for public stops -- needs to be way bigger. For public stops we also have to reduce the icon size on zoom 12 onward

**Comment by gjn** [comment] 2015-12-02 06:43
yes, not easy. It depends really on icon size for points and line thickness for polyline/ploygons.

@ltclm @AFoletti Any way to say, on average, what icon size is? Line thickness?

**Comment by AFoletti** [comment] 2015-12-02 06:54
@gjn  it's very hard to tell a "global" or average value.
In general line thickness is quite small (no more than 2px I would say) with of course some exception (I think sachplan layers have some)
Point is much more variable, and we have symbols which change with zoomlevels. Apart some exceptions (sachplan anyone?) point symbols are generally smaller than 20px

**Comment by loicgasser** [comment] 2015-12-02 07:05
For Agnes points 20px, for adresses 10px. So I would say 10 is probably good.

**Comment by davidoesch** [comment] 2015-12-02 07:24
solution must be

- zoomlevel  dependend
- dataset dependend

the current 5px solution is based on GWR , which works fine on dense areas
as in
https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,true,false,false&layers_timestamp=18641231,,,&X=247214.46&Y=683233.48&zoom=10


icons which are not round as public stops, lubis, kgs, : 20px on zoomlevel
10 onward make sense

**Comment by gjn** [comment] 2015-12-02 07:27
If it's data dependant, we need to handle this information somehwere - most probably in the bod. No easy task to add for all existing layers.

@ltclm @AFoletti thoughts on this?

**Comment by oterral** [comment] 2015-12-02 07:44
My 2 cents on this:

-  Line/Polygon: 5 is good
-  Point: size of the icon  (I don't know if it's possible)

**Comment by AFoletti** [comment] 2015-12-02 07:48
My opinion?
"I have a dream..."
More seriously:
Data dependent is maybe possible, but you have to consider that as "data" you mean "layer". But a layer may have many different point sizes at the same zoomlevel. How do you handle those cases?
Data AND zoomlevel dependent: what you want here is to parse the WMS snippet :stuck_out_tongue_winking_eye: . And you will still have the problem mentioned above.
I think we should stick to a fix tolerance which is more or less adapted for most layers and sincerly I would no go above 10px

**Comment by gjn** [comment] 2016-03-15 13:53
Duplicate of #3065. We close this.

**Closed by gjn** 2016-03-15 13:53 UTC
Labels: 2nd prio, enhancement
