### ISSUE TITLE
Footer link and short name dataowner

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3386] opened 2016-07-01 08:08 UTC
since a lot of CMS url of several offices changed

- Check URL in the (c)  (eg swisstopo gets a 404)
- Check URL in the topic footer (eg swisstopo gets a 404)

![unbenannt](https://cloud.githubusercontent.com/assets/4577727/16515663/97830ca2-3f73-11e6-886f-e7b69184747e.PNG)

**Comment by mariokeusen** [comment] 2016-07-05 09:01
New functional URL's are available in the translation tab now.

**Comment by mariokeusen** [comment] 2016-07-05 09:11
Dunno where the links for the (c)-tool come from btw

**Comment by gjn** [comment] 2016-07-05 10:52
In the footer, there is topic relevant data. They don't change per topic. @davidoesch Do we really want to introduce short text here?
@mariokeusen The text for the footer is also in the translations. It's the *_service_link_label token.

The (c) tool links comes from BOD (if I'm not mistaken) and here, we usually have short names.

**Comment by gjn** [comment] 2016-07-05 11:01
(c) tool links are coming from geocat...I'll write a script to test all current urls and determine the ones that need adaption...

**Comment by mariokeusen** [comment] 2016-07-05 11:26
I did not touch the  *_service_link_label contents at all, since this is content coming from the topic owners. I would not like to change that without a clear need.

**Comment by gjn** [comment] 2016-07-05 12:00
Broken links are a clear need...

**Comment by davidoesch** [comment] 2016-07-05 13:47
Sorry for the confusion: the link defined for the topic can be whatever it is. So it is OK. What I was reporting here: the copyright link in the the map.

**Comment by mariokeusen** [comment] 2016-07-06 05:27
Broken links are fixed in *_service_link_href, but I meant a need for a change of the link-labels

**Comment by gjn** [comment] 2016-07-06 10:16
Here's a list of links of the attributions, that are _not_ 200 responses. The link text is the attribution token in the translation of mf-chsdi3 (coming from bod). Some attributions don't have an URL at all (no_url) and they should be either added to the translations (token.url pattern) or handled correctly in front-end:

@AFoletti where are these URL's come from in the bod?
@mariokeusen Is it correct to have some attributions without urls?
@davidoesch What should happen in front-end if we don't have url defined?

[swisstopo](http://www.swisstopo.admin.ch/internet/swisstopo/de/home.html) gives 302, but is actually 404
[BAZL](http://www.bazl.admin.ch/index.html?lang=de)  gives 302, but is actually 404.
[swisstopo, Kt.](http://www.swisstopo.admin.ch/internet/swisstopo/de/home/swisstopo/org/cartography.html)  gives 302, but is actually 404.
[CNES, Spot Image, swisstopo, NPOC ](http://www.swisstopo.admin.ch/internet/swisstopo/de/home.html)  gives 302, but is actually 404.
[BABS](http://www.bevoelkerungsschutz.admin.ch/internet/bs/de/home/das_babs.html)  gives 303, but is actually 404.
[Amtliche Vermessung Schweiz / FL](http://www.cadastre.ch/internet/cadastre/de/home/products/webmap/cwm.html) gives 404
[BAKOM](http://www.bakom.admin.ch/index.html)  gives 302, but is actually 404.
[ENSI](http://www.bakom.admin.ch/index.html)  gives 301, redirects to https (clap hands...)

[ASTRA + Kanton](no_url)  does not have an URL
[ch.nagra](no_url)  does not have an URL
[swisstopo, Prv.](no_url)  does not have an URL
[BAFU + Kanton](no_url)  does not have an URL
[ch.swisstopo.atlas](no_url)  does not have an URL
[ARE + Kanton](no_url)  does not have an URL
[swisstopo, sgpk](no_url)  does not have an URL
[swisstopo, sgtk](no_url) does not have an URL.
[swisstopo, scnat](no_url) does not have an URL.
[Kantone](no_url)  does not have an URL

Only german links were tested. All languages would need to be adapted.

**Comment by AFoletti** [comment] 2016-07-06 10:39
links come from bod.public.translations table. They are stored with ch.<bundesamt>.url as msg_id

**Comment by mariokeusen** [comment] 2016-07-06 10:58
I'll put together a correct list of all "unique" data owner URL's. @AFoletti : would it be good to handle updates of those URL's similar as the app translations or would you rather leave that information inside the BOD only? Situation: we'll have more dead url's within the next months, since lot of federal offices are changing their cms systems.
@davidoesch : let us discuss what to do with these "combined" data ownerships like ASTRA + Kanton:
no URL and text only? URL of the first mentioned? multiple URLs?...

**Comment by davidoesch** [comment] 2016-07-06 11:09
This has been defined in RE1 as following
- if no URL is defined: then no Link is provided. Just Text as is.
-combined (like ASTRA+ KANTON) : are defined as one Text String, and if no URL is defined for the dataset , then no URL is set. What we can do ad Bund and Canton layers: Link to the federal office since it is the responsible "Fach Stelle"
K.I.S.S.

**Comment by AFoletti** [comment] 2016-07-06 11:18
@mariokeusen : the BOD is the source, but the URLs are then translated and integrated in the chsdi code exactly as every other translation. What you see in mapgeoadmin comes from chsdi, but the source is still the BOD :)
I would leave it that way

**Comment by mariokeusen** [comment] 2016-07-06 11:23
ok @AFoletti : I'll give you a table of all those data owner URL's I could correct in a few minutes...
ok @davidoesch : my proposal for a short term solution for all combined ones: only put blank text in such cases

**Comment by davidoesch** [comment] 2016-07-06 12:20
Ok

**Comment by mariokeusen** [comment] 2016-07-06 12:26
@AFoletti : could you pls replace the urls in bod from the list I just mailed?

**Comment by gjn** [comment] 2016-07-07 08:17
@AFoletti let us know when the bod is adapted and deployed to dev.

**Comment by AFoletti** [comment] 2016-07-07 11:24
links in DB are updated and deployed to DEV

**Comment by gjn** [comment] 2016-07-07 11:36
@davidoesch @mariokeusen Please [Test with this link](https://mf-geoadmin3.dev.bgdi.ch/gjn_attribution/?lang=en&topic=swisstopo&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.geologie-geotechnik-gk500-gesteinsklassierung,ch.bazl.sachplan-infrastruktur-luftfahrt_kraft&layers_opacity=0.75,1&X=226481.36&Y=659634.32&zoom=0). It should contain all the fixes mentioned in this PR.

**Comment by gjn** [comment] 2016-07-07 11:40
hold on...need to update translations in mf-chsdi3...

**Comment by davidoesch** [comment] 2016-07-07 11:44
- provide only domains for offices eg "www.bazl.admin.ch" instead of subsite links "http://www.bazl.admin.ch/index.html?lang=en" -> they are more stable 
- Regression: if we have double mentions like "© Data:swisstopo, swisstopo, sgtk, FOCA" should be only single mention "© Data:swisstopo, sgtk, FOCA".. this was the use case before.

**Comment by gjn** [comment] 2016-07-07 11:51
1) I agree
2) Not a regression. It's the same in [https://map.geo.admin.ch/?lang=en&topic=swisstopo&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.geologie-geotechnik-gk500-gesteinsklassierung,ch.bazl.sachplan-infrastruktur-luftfahrt_kraft&layers_opacity=0.75,1&X=226481.36&Y=659634.32&zoom=0](prod) if those layers are added there. For attribution, there seems to be a difference between `swisstopo` and `swisstopo, sgtk` - at least, we have this distinction currently in the bod. I think this is wanted? @mariokeusen 

We still have other links that are still dead in the translations. I will post a list. I'll also adapt links in the doc (see https://github.com/geoadmin/mf-geoadmin3/issues/3390)

@AFoletti @mariokeusen I will post a list here of the 'old' links.

**Comment by gjn** [comment] 2016-07-07 12:11
@AFoletti @mariokeusen Here's a list of links in the BOD translation tables, that likely need to be adapted as well (they point to old CMS structure)

```
chsdi/locale/de/LC_MESSAGES/chsdi.po|4341| msgstr "http://www.cadastre.ch/internet/kataster/de/home/services/service/wms/cwm.html"
chsdi/locale/de/LC_MESSAGES/chsdi.po|4506| msgstr "http://www.swisstopo.admin.ch/internet/swisstopo/de/home.html"
chsdi/locale/de/LC_MESSAGES/chsdi.po|5157| msgstr "http://www.swisstopo.admin.ch/internet/swisstopo/de/home/swisstopo/org/cartography.html"
chsdi/locale/de/LC_MESSAGES/chsdi.po|5793| msgstr "http://www.vbs.admin.ch/internet/vbs/de/home.html"
chsdi/locale/de/LC_MESSAGES/chsdi.po|5943| msgstr "http://www.geo.admin.ch/internet/geoportal/de/tools/contact.html"
chsdi/locale/de/LC_MESSAGES/chsdi.po|5985| msgstr "http://www.geo.admin.ch/internet/geoportal/de/home/geoadmin/contact.html#copyright"
chsdi/locale/de/LC_MESSAGES/chsdi.po|6264| msgstr "http://www.geo.admin.ch/internet/geoportal/de/commons/help/viewer_help.html"
chsdi/locale/de/LC_MESSAGES/chsdi.po|7341| msgstr "http://www.geo.admin.ch/internet/geoportal/de/home/current.enhRSS.html"
chsdi/locale/en/LC_MESSAGES/chsdi.po|4341| msgstr "http://www.cadastre.ch/internet/kataster/en/home/services/service/wms/cwm.html"
chsdi/locale/en/LC_MESSAGES/chsdi.po|4506| msgstr "http://www.swisstopo.admin.ch/internet/swisstopo/en/home.html"
chsdi/locale/en/LC_MESSAGES/chsdi.po|5157| msgstr "http://www.swisstopo.admin.ch/internet/swisstopo/en/home/swisstopo/org/cartography.html"
chsdi/locale/en/LC_MESSAGES/chsdi.po|5793| msgstr "http://www.vbs.admin.ch/internet/vbs/en/home.html"
chsdi/locale/en/LC_MESSAGES/chsdi.po|5943| msgstr "http://www.geo.admin.ch/internet/geoportal/en/tools/contact.html"
chsdi/locale/en/LC_MESSAGES/chsdi.po|5985| msgstr "http://www.geo.admin.ch/internet/geoportal/en/home/geoadmin/contact.html#copyright"
chsdi/locale/en/LC_MESSAGES/chsdi.po|6264| msgstr "http://www.geo.admin.ch/internet/geoportal/en/commons/help/viewer_help.html"
chsdi/locale/en/LC_MESSAGES/chsdi.po|7341| msgstr "http://www.geo.admin.ch/internet/geoportal/en/home/current.enhRSS.html"
chsdi/locale/fi/LC_MESSAGES/chsdi.po|4341| msgstr "http://www.cadastre.ch/internet/kataster/de/home/services/service/wms/cwm.html"
chsdi/locale/fi/LC_MESSAGES/chsdi.po|4506| msgstr "http://www.swisstopo.admin.ch/internet/swisstopo/de/home.html"
chsdi/locale/fi/LC_MESSAGES/chsdi.po|5157| msgstr "http://www.swisstopo.admin.ch/internet/swisstopo/de/home/swisstopo/org/cartography.html"
chsdi/locale/fi/LC_MESSAGES/chsdi.po|5793| msgstr "http://www.vbs.admin.ch/internet/vbs/de/home.html"
chsdi/locale/fi/LC_MESSAGES/chsdi.po|5943| msgstr "http://www.geo.admin.ch/internet/geoportal/rm/tools/contact.html"
chsdi/locale/fi/LC_MESSAGES/chsdi.po|5985| msgstr "http://www.geo.admin.ch/internet/geoportal/rm/home/geoadmin/contact.html#copyright"
chsdi/locale/fi/LC_MESSAGES/chsdi.po|6264| msgstr "http://www.geo.admin.ch/internet/geoportal/rm/commons/help/viewer_help.html"
chsdi/locale/fi/LC_MESSAGES/chsdi.po|7341| msgstr "http://www.geo.admin.ch/internet/geoportal/rm/home/current.enhRSS.html"
chsdi/locale/fr/LC_MESSAGES/chsdi.po|4341| msgstr "http://www.cadastre.ch/internet/kataster/fr/home/services/service/wms/cwm.html"
chsdi/locale/fr/LC_MESSAGES/chsdi.po|4506| msgstr "http://www.swisstopo.admin.ch/internet/swisstopo/fr/home.html"
chsdi/locale/fr/LC_MESSAGES/chsdi.po|5157| msgstr "http://www.swisstopo.admin.ch/internet/swisstopo/fr/home/swisstopo/org/cartography.html"
chsdi/locale/fr/LC_MESSAGES/chsdi.po|5793| msgstr "http://www.vbs.admin.ch/internet/vbs/fr/home.html"
chsdi/locale/fr/LC_MESSAGES/chsdi.po|5943| msgstr "http://www.geo.admin.ch/internet/geoportal/fr/tools/contact.html"
chsdi/locale/fr/LC_MESSAGES/chsdi.po|5985| msgstr "http://www.geo.admin.ch/internet/geoportal/fr/home/geoadmin/contact.html#copyright"
chsdi/locale/fr/LC_MESSAGES/chsdi.po|6264| msgstr "http://www.geo.admin.ch/internet/geoportal/fr/commons/help/viewer_help.html"
chsdi/locale/fr/LC_MESSAGES/chsdi.po|7341| msgstr "http://www.geo.admin.ch/internet/geoportal/fr/home/current.enhRSS.html"
chsdi/locale/it/LC_MESSAGES/chsdi.po|4341| msgstr "http://www.cadastre.ch/internet/kataster/it/home/services/service/wms/cwm.html"
chsdi/locale/it/LC_MESSAGES/chsdi.po|4506| msgstr "http://www.swisstopo.admin.ch/internet/swisstopo/it/home.html"
chsdi/locale/it/LC_MESSAGES/chsdi.po|5157| msgstr "http://www.swisstopo.admin.ch/internet/swisstopo/it/home/swisstopo/org/cartography.html"
chsdi/locale/it/LC_MESSAGES/chsdi.po|5793| msgstr "http://www.vbs.admin.ch/internet/vbs/it/home.html"
chsdi/locale/it/LC_MESSAGES/chsdi.po|5943| msgstr "http://www.geo.admin.ch/internet/geoportal/it/tools/contact.html"
chsdi/locale/it/LC_MESSAGES/chsdi.po|5985| msgstr "http://www.geo.admin.ch/internet/geoportal/it/home/geoadmin/contact.html#copyright"
chsdi/locale/it/LC_MESSAGES/chsdi.po|6264| msgstr "http://www.geo.admin.ch/internet/geoportal/it/commons/help/viewer_help.html"
chsdi/locale/it/LC_MESSAGES/chsdi.po|7341| msgstr "http://www.geo.admin.ch/internet/geoportal/it/home/current.enhRSS.html"
```

**Comment by mariokeusen** [comment] 2016-07-07 12:23
For 1) don't understand. How to provide lang params like this?
For 2) Gilbert is right, this was a requirement from those specific layers
For the list: where exactly are these URL's being used?

**Comment by gjn** [comment] 2016-07-07 12:24
I assume those URLS are mostly in tooltips...

**Comment by gjn** [comment] 2016-07-07 12:28
New [TestLink](https://mf-geoadmin3.dev.bgdi.ch/gjn_attribution/?api_url=gjn_trans&api_env=dev&lang=en&topic=swisstopo&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.geologie-geotechnik-gk500-gesteinsklassierung,ch.bazl.sachplan-infrastruktur-luftfahrt_kraft&layers_opacity=0.75,1&X=226481.36&Y=659634.32&zoom=0)

**Comment by mariokeusen** [comment] 2016-07-07 12:39
Checked the copyright copyright links and the topic reference links: All ok for the corrections made.

**Comment by oterral** [comment] 2016-08-23 07:29
Thx for the check @mariokeusen

**Closed** 2016-08-23 07:29 UTC
Labels: 2nd prio
