### ISSUE TITLE
3D :webGL crash

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3632] opened 2016-11-24 18:38 UTC
disable cache 
https://mf-geoadmin3.int.bgdi.ch/3dtiles/i

can be reproduced on win10 win7 and latest chrome , just using the navigation buttons

error:

![image](https://cloud.githubusercontent.com/assets/4577727/20607989/91765634-b27d-11e6-9e91-ad42a279ac58.png)

Error in https://mf-geoadmin3.int.bgdi.ch/3dtiles/1472044604/lib/build.js
    at new t (eval at globalEval (build.js:14), <anonymous>:423:18984)
    at new z (eval at globalEval (build.js:14), <anonymous>:460:31360)
    at new me (eval at globalEval (build.js:14), <anonymous>:475:19000)
    at new mh (build.js:590)
    at w (build.js:1694)
    at build.js:1700
    at build.js:227
    at m.$eval (build.js:241)
    at m.$digest (build.js:238)
    at m.$apply (build.js:242)

**Comment by davidoesch** [comment] 2016-11-25 14:31
solved

wrong url

**Comment by davidoesch** [comment] 2016-11-26 10:47
can be reproduced as well with this URL 
https://mf-geoadmin3.int.bgdi.ch/3dtiles/index.html?topic=ech&tileset3d=ch.swisstopo.bridgestest.3d&tilesetTs=20161111&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&lon=7.27597&lat=47.03788&elevation=585&heading=307.793&pitch=-49.168&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bav.haltestellen-oev,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,

use the search to hop from city to city, suddenly Chrome throws an error

**Comment by oterral** [comment] 2016-11-29 10:21
duplicate of #3633

**Closed by oterral** 2016-11-29 10:21 UTC
Labels: 2nd prio, 3D
