### ISSUE TITLE
3D: issue with CWM/terrain

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3057] opened 2016-01-20 09:23 UTC
Might be a terrain issue?
CWM doe snot fit

https://map.geo.admin.ch/?lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.swissimage-product,ch.bafu.permafrost,ch.kantone.cadastralwebmap-farbe&layers_opacity=1,0.55,1&lon=8.29940&lat=47.03688&elevation=1063&heading=201.373&pitch=-46.109&catalogNodes=457,458&layers_visibility=false,false,true.

**Comment by loicgasser** [comment] 2016-01-20 09:30
Well if it were a terrain issue all layers would not fit, related to MapProxy or Cesium.

**Comment by procrastinatio** [comment] 2016-03-16 13:53
It's clearly  a WMS issue, as we are cascading the original WMS source. The source is not configured with gutter support:

- Single Tile WMS
- Adding `gutter` to our WMS (@ltclm is it possible ?)
- Using Mapproxy WMTS/WMTS source as alternative (cache issue ?)

Same view using [WMS](https://map.geo.admin.ch/?lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.kantone.cadastralwebmap-farbe,WMS%7C%7CCadastralWebMap%20(Current,%204356)%7C%7Chttps:%2F%2Fwmts20.prod.bgdi.ch%2Fservice%7C%7Cch.kantone.cadastralwebmap-farbe_current_epsg_4326%7C%7C1.3.0&lon=8.29795&lat=47.03287&elevation=1062&heading=201.373&pitch=-46.109&catalogNodes=457,458&layers_visibility=false,true) from Mapproxy

**Comment by ltclm** [comment] 2016-03-16 13:59
This layer has two cascaded sources:
tlm map -> mapproxy
cadastral webmap -> http://wms.cadastralwebmap.ch/WMS GEOSHOP WMS

Since we dont know how much traffic / requests the geoshop service can handle, we should deactivate this layer for 3d!

**Comment by davidoesch** [comment] 2016-03-16 16:48
cwm is not used that much in 3d--- see last 2 months, so if it breaks we can add larger instances

**Comment by gjn** [comment] 2016-03-16 16:59
I think  http://wms.cadastralwebmap.ch/WMS  is not under our control.

**Comment by davidoesch** [comment] 2016-03-16 17:13
It is - hanspi can scale up the instances. And afaik data Sync should work

**Comment by procrastinatio** [comment] 2016-03-18 18:07
To sum up:
- We provide an Windows Instance + EBS to the third party. The installation, monitoring is not under our control. According to    @hpchrist this should however scale horizontally.
- The GeoShop WMS is unable to do proper gutter, should we use another source (Mapproxy) ?
- Why do we have to cascade this WMS server (performance) ?

**Comment by gjn** [comment] 2016-08-02 11:34
@davidoesch ok to downgrad this?

**Comment by davidoesch** [comment] 2016-08-02 19:10
OK for downgrade

**Comment by davidoesch** [comment] 2017-11-22 16:00
ping @gjn

**Comment by loicgasser** [comment] 2017-11-22 17:29
It's pure WMS and it still is bad.

**Comment by gjn** [comment] 2017-11-24 09:13
Yes?

**Comment by boecklic** [comment] 2019-05-08 08:34
duplicate of https://github.com/geoadmin/mf-geoadmin3/issues/2887

**Closed by boecklic** 2019-05-08 08:34 UTC
Labels: 3D, 3rd prio
