### ISSUE TITLE
newly added ech default layers are draped when loading the page

### ISSUE THREAD

**Issue by ltclm** [geoadmin/mf-geoadmin3#2711] opened 2015-09-25 12:26 UTC
The "featured" default layers of ech topic are shown automatically when switching to 3d mode
https://mf-geoadmin3.dev.bgdi.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,false,false,false&layers_timestamp=18641231,,,&dev3d=true

They are not activated in the layer tree.

**Comment by gjn** [comment] 2015-09-25 12:32
Duplicate of https://github.com/geoadmin/mf-geoadmin3/issues/2692

Will be fixed with #2710.

**Closed by gjn** 2015-09-25 12:32 UTC
Labels: 3D
