### ISSUE TITLE
Share: incl marker from swisssearch result

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3354] opened 2016-06-02 11:15 UTC
ALL OS
ALL Browsers

step to reproduce

open application

Add "seftigenstrasse 264" in search
select address

map with marker is shown

Share map via share function

Result:
Address is not hghlighted

Expected result
Swissearch selected result is included " Use case:  I search an address and share it as a result"

**Comment by loicgasser** [comment] 2016-06-02 15:29
I agree it's a very common use case.

There currently no easy way to achieve that. we could use the crosshair but the page will then be centered on the address.
To keep the position of the map and the marker at the correct location we would need two extra permalink parameters.

I would propose to add two extra permalink parameters.

Xsearch and Ysearch. this way we could even link a search result without an iframe.
@gjn @oterral thoughts?

I could take care of it.

**Comment by davidoesch** [comment] 2016-06-02 15:40
use the swisssearch with : limit=1 parameter?

**Comment by gjn** [comment] 2016-06-02 15:51
limit: 1 will not help, was the selection of the user might not have been the first result.

We already have a way to put a marker on the map via the PL: 'crosshair=xxx'. Let's use it by having it in the PL as long as  the search marker is on the map.

BUT: It's third priority - so let's do all the other stuff first.

**Comment by gjn** [comment] 2016-06-02 18:14
Of course, crosshair will only be correct for as long as the map is not moved. When it's moved, then it would not longer be valid. (As @loicgasser noted in his comment)

**Comment by oterral** [comment] 2016-08-23 07:35
Logically if we select `Seftigenstrasse 264 3084 Wabern' in search result we should add the swissearch parameter to permalink: `` swisssearch=Seftigenstrasse%20264%203084%20Wabern`

Then if you share the permalink with this swissearch you've the marker: https://mf-geoadmin3.dev.bgdi.ch?api_url=gjn_trans&swisssearch=Seftigenstrasse%20264%203084%20Wabern`

If the swisssearch is enough precise it should return only one result.

**Comment by davidoesch** [comment] 2016-08-23 07:46
I would not add swisssearch paramtere in the PL. simply it does not solve the issue the user has.  we  add location support in permalink (and alter on maybe address) in a first step with geoseo...but his is another project. so for now : let it as it is

**Comment by oterral** [comment] 2016-08-23 08:05
we could also improve crosshair functionnality using `crosshair=marker,x,y` , shoudln't be hard.

**Comment by davidoesch** [comment] 2016-08-23 08:06
Backward compatibility?

**Comment by oterral** [comment] 2016-08-23 09:02
if `x`or `y` are not present we use the default behavior

**Comment by davidoesch** [comment] 2016-09-02 07:05
OK in this case: a clear go

**Comment by davidoesch** [comment] 2017-11-22 16:06
ping @oterral , since #4002 is closed now

**Comment by boecklic** [comment] 2019-05-08 08:41
duplicate of https://github.com/geoadmin/mf-geoadmin3/issues/4666

**Closed by boecklic** 2019-05-08 08:41 UTC
Labels: 3rd prio, enhancement
