### ISSUE TITLE
3D bgLayer=voidLayer does not work

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2899] opened 2015-11-17 08:31 UTC
test
https://mf-geoadmin3.int.bgdi.ch/3dalpha/?topic=ech&lang=de&bgLayer=voidLayer&layers=ch.bafu.flussordnungszahlen-strahler&lon=8.54986&lat=47.24503&elevation=9890&heading=159.434&pitch=-27.869&layers_opacity=0.75

expected result:

no tlm shown as bg

**Comment by cedricmoullet** [comment] 2015-11-17 08:33
I think it's fixed in the trunk

**Comment by gjn** [comment] 2015-11-17 09:50
It's duplicate of https://github.com/geoadmin/mf-geoadmin3/issues/2837, which is fixed in current master.

**Comment by gjn** [comment] 2015-11-17 09:50
It's duplicate of https://github.com/geoadmin/mf-geoadmin3/issues/2837, which is fixed in current master.

**Closed by gjn** 2015-11-17 09:50 UTC
Labels: 2nd prio, 3D, bug
