### ISSUE TITLE
Tooltip: 2d footprint of highlight visible

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2715] opened 2015-09-27 09:59 UTC
https://mf-geoadmin3.dev.bgdi.ch/?dev3d=true&topic=geol&lang=fr&bgLayer=ch.swisstopo.pixelkarte-grau&lon=7.14721&lat=46.08595&elevation=6990&heading=286.274&pitch=-24.682&layers=ch.swisstopo.swissimage-product

although it is a nice feature, for the normal user this will be to complex to understands

![unbenannt](https://cloud.githubusercontent.com/assets/4577727/10122164/28b7b406-650f-11e5-9eea-fff623d91ccb.PNG)

**Comment by gjn** [comment] 2015-09-27 11:21
That's a bug.

**Comment by oterral** [comment] 2015-10-06 13:47
Line clamped to ground not yet available in Cesium

**Comment by mariokeusen** [comment] 2015-11-17 09:42
Reproduced on all browsers on apple OSX. For me this is also a bug.
Expected: highlight outline fits to the highlight fill geometry.

**Comment by oterral** [comment] 2016-01-19 13:43
Feature is planned on top of the Cesium todo list for 2016.

**Comment by gjn** [comment] 2016-03-15 14:01
#3104 is the same. Missing clampToGround support in Cesium.

**Comment by oterral** [comment] 2016-04-27 15:16
Duplicate of #3104

**Closed by oterral** 2016-04-27 15:16 UTC
Labels: 2nd prio, 3D, bug
