### ISSUE TITLE
LFP 1

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3574] opened 2016-10-26 10:50 UTC
FPDS data as https://map.geo.admin.ch/?layers=ch.swisstopo.fixpunkte-lfp1&topic=ech&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe 
are shifted on mobile ( but not on desktop)
![image](https://cloud.githubusercontent.com/assets/4577727/19723260/b7f29760-9b7a-11e6-93ec-83e2a7284987.png)

confirmed on latest chrome for android and 7.0 and nexus 6P  
other customers are conforming this https://twitter.com/MikeSchudel/status/791223053808173056

**Comment by gjn** [comment] 2016-10-26 10:51
Duplicate of https://github.com/geoadmin/mf-chsdi3/issues/2263, which will be solved by today's deploy.

**Closed by gjn** 2016-10-26 10:51 UTC
Labels: 1st prio, bug

**Comment by gjn** [comment] 2016-10-26 13:56
Fixed on prod now.
