### ISSUE TITLE
feedback mail permalink is truncated

### ISSUE THREAD

**Issue by ltclm** [geoadmin/mf-geoadmin3#2151] opened 2015-02-13 09:58 UTC
The permalink seems to be truncated in the feedback mail:
p.e.
```

-----Ursprüngliche Nachricht-----
Von: webgis@swisstopo.ch [mailto:webgis@swisstopo.ch] 
Gesendet: Donnerstag, 12. Februar 2015 16:42
An: _swisstopo-webgis
Betreff: Customer feedback

tobias.kellenberger@swisstopo.ch just sent a feedback:
 Liebe Kollegen, in den ho??chsten zwei Zoomstufen swissimage Luftbild Hintergrund: Die Bildkachel ist fehlerhaft

Besten Gruss Tobias. 
Permalink: http://map.geo.admin.ch/?X=177482.55&Y=610810.89&zoom=13&lang=de&topic=ech&bgLayer=ch.swisstopo.swissimage&catalogNodes=457,485,508,517,458&layers=ch.swisstopo.lubis-bildstreifen&layers_timestamp=. 

User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3; rv:11.0) like Gecko

```

As a result most of the received permalinks are not usable.

**Comment by ltclm** [comment] 2015-02-13 10:01
the same in the attached meta.json
```json
{  
   "body":"Liebe Kollegen, in den h\u00f6chsten zwei Zoomstufen swissimage Luftbild Hintergrund: Die Bildkachel ist fehlerhaft\n\nBesten Gruss Tobias",
   "permalink":"http://map.geo.admin.ch/?X=177482.55&Y=610810.89&zoom=13&lang=de&topic=ech&bgLayer=ch.swisstopo.swissimage&catalogNodes=457,485,508,517,458&layers=ch.swisstopo.lubis-bildstreifen&layers_timestamp=",
   "attachement":"",
   "kml":"",
   "emailAddress":"tobias.kellenberger@swisstopo.ch",
   "date":"2015-02-12 16:41",
   "userAgent":"Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3; rv:11.0) like Gecko"
}
```

**Comment by gjn** [comment] 2015-02-13 12:02
This seems browser specific. Tested on chrome and it was good. FF not so much.

**Comment by gjn** [comment] 2015-02-18 08:00
@ltclm Can't reproduce anymore. Do you have a link when it happens?

**Comment by ponceta** [comment] 2015-02-18 08:05
http://mf-geoadmin3.int.bgdi.ch/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&X=190000.00&Y=660000.00&zoom=1&catalogNodes=457,532&layers_opacity=0.75,1,0.75,1,1,1,1,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,1,0.75,0.75,1,1,0.75&layers=ch.bafu.naqua-grundwasser_psm,ch.bafu.bundesinventare-amphibien_anhang4,ch.bafu.bundesinventare-amphibien,ch.bafu.bundesinventare-amphibien_wanderobjekte,ch.bafu.fischerei-aeschen_kernzonen,ch.bafu.fischerei-aeschen_laichplaetze,ch.bafu.fischerei-aeschen_larvenhabitate,ch.blw.klimaeignung-futterbau,ch.blw.klimaeignung-getreidebau,ch.blw.klimaeignung-kartoffeln,ch.blw.klimaeignung-koernermais,ch.blw.klimaeignung-kulturland,ch.blw.klimaeignung-spezialkulturen,ch.blw.klimaeignung-typ,ch.blw.klimaeignung-zwischenfruchtbau,ch.bafu.nabelstationen,ch.blw.niederschlagshaushalt,ch.bafu.laerm-bahnlaerm_tag,ch.bav.kataster-belasteter-standorte-oev,ch.bafu.schutzgebiete-biosphaerenreservate,ch.bafu.laerm-bahnlaerm_nacht&http://mf-geoadmin3.int.bgdi.ch/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&X=190000.00&Y=660000.00&zoom=1&catalogNodes=457,532&layers_opacity=0.75,1,0.75,1,1,1,1,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,1,0.75,0.75,1,1,0.75&layers=ch.bafu.naqua-grundwasser_psm,ch.bafu.bundesinventare-amphibien_anhang4,ch.bafu.bundesinventare-amphibien,ch.bafu.bundesinventare-amphibien_wanderobjekte,ch.bafu.fischerei-aeschen_kernzonen,ch.bafu.fischerei-aeschen_laichplaetze,ch.bafu.fischerei-aeschen_larvenhabitate,ch.blw.klimaeignung-futterbau,ch.blw.klimaeignung-getreidebau,ch.blw.klimaeignung-kartoffeln,ch.blw.klimaeignung-koernermais,ch.blw.klimaeignung-kulturland,ch.blw.klimaeignung-spezialkulturen,ch.blw.klimaeignung-typ,ch.blw.klimaeignung-zwischenfruchtbau,ch.bafu.nabelstationen,ch.blw.niederschlagshaushalt,ch.bafu.laerm-bahnlaerm_tag,ch.bav.kataster-belasteter-standorte-oev,ch.bafu.schutzgebiete-biosphaerenreservate,ch.bafu.laerm-bahnlaerm_nacht,WMS%7C%7CKreisgrenzen%7C%7Chttp:%2F%2Fmapserver1.gr.ch%2Fwms%2Fadmineinteilung%3F%7C%7CKreisgrenzen,KML%7C%7Chttp:%2F%2Fopendata.utou.ch%2Furbanproto%2Fgeneva%2Fgeo%2Fkml%2FRoutes.kml for example

**Comment by gjn** [comment] 2015-02-19 15:03
Can't reproduce. Also, in your example ,the link is complete. It's just that it's broken into parts in the email client. So it's a problem in the email client and not in the feedback service.

It's also possible that the email client re-formats the message when replying and/or forwarding the email. Again, there's nothing we can do about that.

We could send the email in html format, but that might break topo integration yet again.

@ltclm @ponceta Please try to reproduce once again. If not possible, please close this.

**Comment by ltclm** [comment] 2015-02-19 15:31
me neither,
tried some long urls like:
http://map.geo.admin.ch/?X=190000.00&Y=660000.00&zoom=1&lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-farbe&catalogNodes=457,458,477,485&layers=ch.swisstopo.zeitreihen,ch.swisstopo.pixelkarte-farbe-pk1000.noscale,ch.swisstopo.pixelkarte-farbe-pk200.noscale,ch.swisstopo.pixelkarte-farbe-pk100.noscale,ch.swisstopo.pixelkarte-farbe-pk500.noscale,ch.swisstopo.pixelkarte-farbe-pk50.noscale,ch.swisstopo.pixelkarte-pk500.metadata,ch.swisstopo.pixelkarte-farbe-pk25.noscale,ch.swisstopo.pixelkarte-pk200.metadata,ch.swisstopo.pixelkarte-pk100.metadata,ch.swisstopo.pixelkarte-pk50.metadata,ch.swisstopo.pixelkarte-pk25.metadata,ch.swisstopo.swisstlm3d-karte-farbe,ch.swisstopo.swisstlm3d-karte-grau,ch.swisstopo.hiks-dufour,ch.swisstopo.hiks-siegfried,ch.swisstopo.vec200-miscellaneous,ch.kantone.cadastralwebmap-farbe,ch.swisstopo.vec200-miscellaneous-geodpoint,ch.bfs.arealstatistik-1985,ch.bfs.arealstatistik-bodenbedeckung-1985,ch.bfs.arealstatistik-bodennutzung-1985,ch.bfs.arealstatistik-1997,ch.bfs.arealstatistik-bodenbedeckung-1997,ch.bfs.arealstatistik-bodennutzung-1997,ch.bfs.arealstatistik-bodenbedeckung,ch.bfs.arealstatistik,ch.bfs.arealstatistik-bodennutzung,ch.bafu.biogeographische_regionen,ch.swisstopo.vec25-primaerflaechen,ch.swisstopo.vec200-landcover,ch.bfs.arealstatistik-hintergrund,ch.bfs.arealstatistik-waldmischungsgrad,ch.swisstopo.images-swissimage.metadata,ch.swisstopo.lubis-luftbilder-dritte-kantone,ch.swisstopo.lubis-luftbilder-dritte-firmen,ch.swisstopo.lubis-luftbilder_farbe,ch.swisstopo.lubis-luftbilder_infrarot,ch.swisstopo.lubis-luftbilder_schwarzweiss,ch.swisstopo.lubis-bildstreifen&time=1864&layers_timestamp=18641231,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,1864&layers_opacity=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,1,1,1,1,1,1,1
etc.
they are not truncated in the mail.
this url is not displayed correctly in the mail client but the meta.json contains the complete url. We should ensure that the igis interface is using the meta.json permalink.
From my side we can close this ticket.

**Closed** 2015-02-19 19:25 UTC
Labels: bug prio 1
