### ISSUE TITLE
Time table dashboard not correct

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3653] opened 2016-12-11 09:44 UTC
Hi
Some depart hours are missing 

Eg, rueggisberg tahn , on 1035

Here or service
![screenshot_20161211-103930](https://cloud.githubusercontent.com/assets/4577727/21079296/8053b3f6-bf8e-11e6-9063-10d6263e64fb.png)

Official time table

![screenshot_20161211-103942](https://cloud.githubusercontent.com/assets/4577727/21079302/a046518c-bf8e-11e6-8546-9cd7c8620fbc.png)

So all the morning times are missing:

Related to the fahrplanwechsel ?

**Comment by AFoletti** [comment] 2016-12-12 05:08
looks OK now.
even if it was fahrplanwechsel-related should not happen.

**Comment by davidoesch** [comment] 2016-12-12 06:38
Still wrong here... Chrome on Android 7.1.1.
Can you double check on iOS @ced

**Comment by oterral** [comment] 2016-12-12 07:46
@AFoletti still not ok.
It's not geoadmin or browser or OS related.

Test with this:
https://mf-chsdi3.int.bgdi.ch/stationboard/stops/8571402?destination=K%C3%B6niz%2C%20Bahnhof

**Comment by AFoletti** [comment] 2016-12-12 08:03
we are both right... In the data there is a hole between 7:17 and 15:39. Since I looked before 6:00 I did not see anything strange.

Anyhow, problem is the data.
Could someone in Wabern please check the original zip file? Our database is clearly wrong and if the original data is wrong too then we have to contact geOps

**Comment by oterral** [comment] 2016-12-12 08:08
Who is responsible of the data integration of this @alcapat  @ltclm ?

**Comment by ltclm** [comment] 2016-12-12 10:03
The problem is the original data:

this is what we have in the original zip file (``121M Dez 11 22:05 departures.zip``): 
```bash
$ cat  departures.csv | awk  -F"," '$1 ~ /8571402/ {print $0}' | grep "\"Köniz"
8571402,2016-12-12T23:39:00+01:00,3,631,"Köniz, Bahnhof","Rüeggisberg, Than; Oberbütschel; Bütschel, Gschneit; Bütschel, Abzw.; Niedermuhlern, Baumgärtli; Niedermuhlern, Käserei; Niedermuhlern, Bachmühle; Oberbalm, Bach; Oberscherli, Leimen; Oberbalm, Dorf; Oberscherli, Leimen; Scherliau; Oberscherli, Dorf; Schlatt bei Gasel; Schliern bei Köniz; Köniz, Schloss; Köniz, Zentrum"
8571402,2016-12-12T16:39:00+01:00,3,631,"Köniz, Bahnhof","Rüeggisberg, Than; Oberbütschel; Bütschel, Gschneit; Bütschel, Abzw.; Niedermuhlern, Baumgärtli; Niedermuhlern, Käserei; Niedermuhlern, Bachmühle; Oberbalm, Bach; Oberscherli, Leimen; Oberbalm, Dorf; Oberscherli, Leimen; Scherliau; Oberscherli, Dorf; Schlatt bei Gasel; Schliern bei Köniz; Köniz, Schloss; Köniz, Zentrum"
8571402,2016-12-12T06:09:00+01:00,3,631,"Köniz, Bahnhof","Rüeggisberg, Than; Oberbütschel; Bütschel, Gschneit; Bütschel, Abzw.; Niedermuhlern, Baumgärtli; Niedermuhlern, Käserei; Niedermuhlern, Bachmühle; Oberbalm, Bach; Oberscherli, Leimen; Oberbalm, Dorf; Oberscherli, Leimen; Scherliau; Oberscherli, Dorf; Schlatt bei Gasel; Schliern bei Köniz; Köniz, Schloss; Köniz, Zentrum"
8571402,2016-12-12T15:39:00+01:00,3,631,"Köniz, Bahnhof","Rüeggisberg, Than; Oberbütschel; Bütschel, Gschneit; Bütschel, Abzw.; Niedermuhlern, Baumgärtli; Niedermuhlern, Käserei; Niedermuhlern, Bachmühle; Oberbalm, Bach; Oberscherli, Leimen; Oberbalm, Dorf; Oberscherli, Leimen; Scherliau; Oberscherli, Dorf; Schlatt bei Gasel; Schliern bei Köniz; Köniz, Schloss; Köniz, Zentrum"
```
which is imported to the database:
```sql
psql -h pg-0.dev.bgdi.ch -U pgkogis -d uvek_master -c "select stop,time,destination FROM bav.oev_departures where stop = 8571402 and destination like 'Köniz%' order by 2 asc"
  stop   |        time         |  destination
---------+---------------------+----------------
 8571402 | 2016-12-12 06:09:00 | Köniz, Bahnhof
 8571402 | 2016-12-12 15:39:00 | Köniz, Bahnhof
 8571402 | 2016-12-12 16:39:00 | Köniz, Bahnhof
 8571402 | 2016-12-12 23:39:00 | Köniz, Bahnhof
(4 Zeilen)

```

**Comment by davidoesch** [comment] 2016-12-12 10:04
ok, can you drop a mail to geops and cc BAV?

**Comment by ltclm** [comment] 2016-12-13 08:27
the missing data issue has been solved by geops and the data has been re-imported.
```sql
$ psql -h pg-0.dev.bgdi.ch -U pgkogis -d uvek_master -c "select stop,time,destination FROM bav.oev_departures where stop = 8571402 and destination like 'Köniz%' order by 2 asc"
  stop   |        time         |  destination
---------+---------------------+----------------
 8571402 | 2016-12-13 06:09:00 | Köniz, Bahnhof
 8571402 | 2016-12-13 06:39:00 | Köniz, Bahnhof
 8571402 | 2016-12-13 07:39:00 | Köniz, Bahnhof
...
 8571402 | 2016-12-16 21:39:00 | Köniz, Bahnhof
 8571402 | 2016-12-16 22:39:00 | Köniz, Bahnhof
 8571402 | 2016-12-16 23:39:00 | Köniz, Bahnhof
(73 Zeilen)
```

**Comment by oterral** [comment] 2016-12-13 08:28
Fixed on prod. thx @ltclm .

**Closed by oterral** 2016-12-13 08:28 UTC
Labels: 1st prio
