### ISSUE TITLE
KML OGC issue

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3549] opened 2016-10-17 07:58 UTC
Try to load
https://traildevils.ch/Track/Export/KML/7dd4a6da5082ccf440e408d34823e0e5

from URL or local storage

Error:
OGC Proxy

It used to work before last deploy

Workaround
import the KML to google my maps then export it as kml. then it works

**Comment by oterral** [comment] 2016-10-17 08:36
it seems it's an ogcproxy error to me.

**Comment by gjn** [comment] 2016-10-18 11:33
Seems like the resource doesn't exist or there's some other problems. Accessing it directly:

```
curl -I https://traildevils.ch/Track/Export/KML/7dd4a6da5082ccf440e408d34823e0e5
HTTP/1.1 500 Internal Server Error
Cache-Control: private
Content-Length: 5648
Content-Type: text/html; charset=utf-8
X-Powered-By-Plesk: PleskWin
Strict-Transport-Security: max-age=16070400
Date: Tue, 18 Oct 2016 11:27:58 GMT
```

Anyhow, one can download the kml with browser just fine and then import via Drag&Drop. So I guess the kml itself is fine.

I assume the traildevils server changed some settings preventing the download of a kml outside of a browser context. Would need to be analysed further.

**Comment by oterral** [comment] 2016-10-19 06:38
Interesting. So probably it's not a bug on our side.

**Comment by davidoesch** [comment] 2016-10-19 08:31
Customer has been informed

**Comment by gjn** [comment] 2016-10-19 09:43
If CORS is well supported, we could hack an exception for traildevils.ch to bypass our ogcproxy. Then it will probably work, as we are in browser context for the download.

**Comment by davidoesch** [comment] 2016-10-19 09:55
The Problem should be fixed at the source... No exception

**Comment by gjn** [comment] 2016-10-19 09:58
Not sure. We should probably find a way to find out quickly if a certain source support CORS or not. Right now, the test wether to use the ogcproxy or not is very simple only looking at the URL. But probably sending out an OPTIONS or HEAD request might be rapid enough to determine if CORS is supported.

I think that would be the propper solution, if it performs well.

**Comment by gjn** [comment] 2016-10-19 10:01
No CORS support for traildevils.ch...

**Comment by oterral** [comment] 2016-10-25 07:46
@gjn ` curl -I ` doens't work because the HEAD request is not supported. but a simple `curl  https://traildevils.ch/Track/Export/KML/7dd4a6da5082ccf440e408d34823e0e5` works as expected.

Does the ogc prox a HEAD request ?  @procrastinatio

**Comment by procrastinatio** [comment] 2016-10-25 15:37
The problem is not ogcproxy, but the source:

```
$ curl -I https://traildevils.ch/Track/Export/KML/ce0a7dffd962cfa3ba8308d3482fbd49
HTTP/1.1 500 Internal Server Error
```

**Comment by oterral** [comment] 2016-10-25 15:40
Read my previous comment.

**Comment by loicgasser** [comment] 2016-10-25 15:50
I think there is an issue in ogcproxy. But I don't want to invest too much time on the current solution as we'll have a generic one for all our applications.

**Comment by procrastinatio** [comment] 2016-10-25 16:44
Ogcproxy error could be more friendly, but anyway I'll get this nasty error:
```
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): traildevils.ch
('Connection aborted.', error(104, 'Connection reset by peer'))
```

**Comment by loicgasser** [comment] 2016-10-25 16:48
Yes and for some reasons a simple Get fails with 'httplib' but works with the 'requests' module.

**Comment by procrastinatio** [comment] 2016-10-26 06:55
@loicgasser Everything fails on our Debian wheezy: httplib2, urllib2, requests. But everything is going fine on debian Jessie. I won't investigate any further.

**Comment by gjn** [comment] 2016-10-26 06:59
CORS is complicated. Might be that an OPTIONS requests is needed before doing the actual GET request for it to work.

But this particular problem here seems to me a server configuration. They have some fancy logic to avoid that other people use their KMLs. As they are informed, we close this.

**Closed by gjn** 2016-10-26 06:59 UTC
Labels: 3rd prio, bug
