### ISSUE TITLE
3D WEBGL and IE11

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3635] opened 2016-11-29 08:21 UTC
Hi there

under IE11 bureuaut
this branch
https://mf-geoadmin3.int.bgdi.ch/3dtiles/index.html?topic=ech&tileset3d=ch.swisstopo.bridgestest.3d&tilesetTs=20161111&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&lon=7.44072&lat=46.95138&elevation=600&heading=20.853&pitch=-14.600&layers_visibility=false&layers_timestamp=18641231 

does not load at all 
![image](https://cloud.githubusercontent.com/assets/4577727/20701799/28f1303e-b615-11e6-9ca4-9038fab1caa0.png)

related to #3633 

whereas this one here

https://mf-geoadmin3.int.bgdi.ch/3dtiles/index.html?topic=ech&lang=fr&bgLayer=ch.swisstopo.pixelkarte-farbe&layers_visibility=false&layers_timestamp=18641231&lon=6.63588&lat=46.92545&elevation=911&heading=65.813&pitch=-31.443
does work

**Comment by oterral** [comment] 2016-11-29 10:16
Duplicate of #3633

**Closed by oterral** 2016-11-29 10:16 UTC
Labels: 1st prio, 3D
