### ISSUE TITLE
[MVT] background switcher: searching a location with the coodinates fails

### ISSUE THREAD

**Issue by Brunim28** [geoadmin/mf-geoadmin3#4621] opened 2018-12-03 15:40 UTC
OS: WIN10 / browser: Edge
Test 7 -> Issue: 
Luftbilder can be loaded successfully but when searching a location with the coordinates, a blank map appears, excepted the red arrow of the location (centred on the map). Thus, zooming on it doesn't work. 

To reproduce: 
1. Open application
2. Switch Background to SWISSIMAGE
3. Zoom to 891658 323565.8

Expected Results: 
2. Aerial imagery appears
3. Aerial imagery appears also on large zoomlevels

**Comment by loicgasser** [comment] 2018-12-04 00:40
Yes try with https://github.com/geoadmin/mf-geoadmin3/pull/4613

Fixed in
https://github.com/geoadmin/mf-geoadmin3/pull/4613

I think this is a duplicate of

https://github.com/geoadmin/mf-geoadmin3/issues/4606

**Comment by davidoesch** [comment] 2018-12-04 15:03
@Brunim28 fixed from your point of view?

**Comment by Brunim28** [comment] 2018-12-04 15:59
@davidoesch If the red arrow must be in Germany (Starnberg), then yes, fixed from my point of view! Sorry for the late answer

**Comment by loicgasser** [comment] 2018-12-05 12:32
Fiwed

**Closed by loicgasser** 2018-12-05 12:32 UTC
Labels: bug
