### ISSUE TITLE
Height in profile doesn't correspond to height in popup

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-geoadmin3#4150] opened 2018-02-09 15:47 UTC
As in the title:

https://s.geo.admin.ch/78a696a150
Height of the point in popup (right click) is 1406 and doesn't correspond to height in profile.

But if you trace a profile at  more detailed scale than it's ok: https://s.geo.admin.ch/78a699d23f

**Comment by p1d1d1** [comment] 2018-02-09 15:52
PS: it does work when you take just a couple of height curves for the profile

**Comment by loicgasser** [comment] 2018-02-09 16:16
yes it is due to resampling. it is too much data for the server and client to handle otherwise. I think it's a wontfix

**Comment by davidoesch** [comment] 2018-02-09 16:21
duplicate of https://github.com/geoadmin/mf-geoadmin3/issues/3743

**Closed by davidoesch** 2018-02-09 16:21 UTC
