### ISSUE TITLE
JSON Layer Order

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4200] opened 2018-03-15 08:52 UTC
Issue:

Here the Icon is transparent
<iframe src="https://mf-geoadmin3.int.bgdi.ch/meteo_temp/embed.html?api_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Fmeteo_temp&lang=de&topic=ech&bgLayer=voidLayer&layers=ch.bafu.gefahren-basiskarte,ch.meteoschweiz.messnetz-automatisch&ch.meteoschweiz.messnetz-automatisch=AIR&showTooltip=false&zoom=1.25&&layers_opacity=0.5,1"></iframe>

Expected result 

ico is not transparent

<iframe src="https://mf-geoadmin3.int.bgdi.ch/meteo_temp/embed.html?api_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Fmeteo_temp&lang=de&topic=ech&bgLayer=voidLayer&layers=ch.bafu.gefahren-basiskarte,ch.meteoschweiz.messnetz-automatisch&zoom=1.25&&layers_opacity=0.5,1,1"></iframe>

-> assumption is: if station paramter is loaded : icons become transparent. This hould NOT be the case

**Comment by loicgasser** [comment] 2018-03-15 09:00
Actually the problem is the layer order. GIN map moves on top of the icon, which make it look transparent.

**Comment by davidoesch** [comment] 2018-03-15 09:05
Ahhhhhh my fault
@Zeix: you have to move the layer order at the end

**Comment by mbuehrig** [comment] 2018-03-15 09:15
@loicgasser @davidoesch:
How exactly?
https://mf-geoadmin3.int.bgdi.ch/meteo_temp/embed.html?api_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Fmeteo_temp&lang=<@lang@>&topic=ech&bgLayer=voidLayer&showTooltip=true&zoom=1.9&Y=130713&X=560401&layers_opacity=0.5,1&layers=ch.bafu.gefahren-basiskarte,ch.meteoschweiz.messnetz-automatisch&ch.meteoschweiz.messnetz-automatisch=AIG

**Comment by davidoesch** [comment] 2018-03-15 10:03
https://mf-geoadmin3.int.bgdi.ch/meteo_temp/mobile.html?api_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Fmeteo_temp&lang=de&topic=ech&bgLayer=voidLayer&zoom=6&layers_opacity=0.5,1&layers=ch.bafu.gefahren-basiskarte,ch.meteoschweiz.messnetz-automatisch&E=2560401.00&N=1130713.00

**Comment by mbuehrig** [comment] 2018-03-15 10:12
Still doesn't work for me. Layer opacity is wrong. The URL sent by @davidoesch is not working for me. And the coordinates i have are not the East and North they are X and Y. (different format)

https://mf-geoadmin3.int.bgdi.ch/embed.html?api_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Fmeteo_temp&lang=de&topic=ech&bgLayer=voidLayer&zoom=1.9&showTooltip=true&layers_opacity=0.5,1&layers=ch.bafu.gefahren-basiskarte,ch.meteoschweiz.messnetz-automatisch&ch.meteoschweiz.messnetz-automatisch=AMW&Y=268304&X=741796

**Comment by davidoesch** [comment] 2018-03-15 10:15
The layers parameter have to be set 

https://mf-geoadmin3.int.bgdi.ch/embed.html?api_url=%2F%2Fmf-chsdi3.dev.bgdi.ch%2Fmeteo_temp&lang=de&topic=ech&bgLayer=voidLayer&zoom=1.9&showTooltip=true&layers_opacity=0.5,1&layers=ch.meteoschweiz.messnetz-automatisch,ch.bafu.gefahren-basiskarte&@ch.meteoschweiz.messnetz-automatisch=AMW&Y=268304&X=741796


See the layer order above

**Comment by mbuehrig** [comment] 2018-03-15 10:25
Now the icons are always transparent, According to the ux-concept they should be non-transparent all the time. 

https://screenshots.firefox.com/NIfchDewFNFn3QFO/0.0.0.0

**Comment by loicgasser** [comment] 2018-03-15 10:28
yes it is a bug. The "GIN" layer is placed on top of the "meteo" layer". Some timing issue in the permalink.
Will be fixed soon.

**Comment by oterral** [comment] 2018-03-15 10:46
What is the name of the "GIN" layer ?

**Comment by loicgasser** [comment] 2018-03-15 10:57
ch.bafu.gefahren-basiskarte

**Closed** 2018-03-20 14:14 UTC
Labels: 2nd prio, bug
