### ISSUE TITLE
No data in Payerne ?

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#3383] opened 2016-06-30 12:06 UTC
I'm surprised not to see data in Payerne for this layer: https://s.geo.admin.ch/6ccc8e20bd
Is the layer correct ?

**Comment by gjn** [comment] 2016-06-30 12:11
Strange indeed. I only see something around Locarno.

**Comment by ltclm** [comment] 2016-06-30 12:44
the layer configuration is right.
This layer shows all features of  ``uvek.bazl.laermbelastungskataster_zivilflugplaetze`` with ``exposuregroup_exposuretype like 'OverallTrafficMilitary_Lr'```.
It's probably an error in the delivered data, because there is no data at all from payerne.

**Comment by mariokeusen** [comment] 2016-06-30 13:53
I can confirm that the data is not available for all existing civil and military airport facilities. As far as I know BAZL has running (political) approval procedures for each and every facility. As soon as one of those procedures is accepted, a data update will follow. Consider these layers as a data collection which is growing with each decision. May I therefore close this issue?

**Closed** 2016-06-30 13:57 UTC
Labels: 2nd prio

**Comment by davidoesch** [comment] 2016-07-12 15:22
it is missing for ALP and BUO as well: dataset is not complete according to BAZL
