### ISSUE TITLE
[layertree/layerselection] not the same layer title in selection and layertree

### ISSUE THREAD

**Issue by mariokeusen** [geoadmin/mf-geoadmin3#3298] opened 2016-04-29 08:10 UTC
UC: open https://map.geo.admin.ch/?topic=swisstopo&lang=de&bgLayer=ch.swisstopo.pixelkarte-farbe&catalogNodes=1538&layers=ch.swisstopo.wk50-papierkarte.metadata , look at the layertree/catalog and the name of the activated layer, look at the name of the layer in the selection
Result: not the same layer name in selection and catalog (yes, there is also an error in geocat, in DE there is a RM alternativtitle, data owner is informed to solve this)
Expected: it is always the same layer name and language in catalog and selection
![layertreeselectionissue_20160429](https://cloud.githubusercontent.com/assets/4577749/14911028/b9d7d7f4-0df2-11e6-8445-68d86dbcac2c.PNG)

**Comment by AFoletti** [comment] 2016-04-29 11:13
@mariokeusen you already found the geocat problem.
About the difference, I really don't know what to say. The two are coupled by a trigger in the BOD, which seems to have not worked in this case (we should have had the RM version in the selection too).
I cant reproduce the mishap, since the trigger reacts correctly every time I call it.
To sum up: I fixed the issue but I'm unable to see the reason of it. Maybe @ltclm ?

**Comment by ltclm** [comment] 2016-05-02 06:37
it is hard to find the reason for the problem.
The catalog translation comes directly from the bod (re3.view_catalog). Currently the bod entries for this layer is wrong on prod and fixed on dev (thanks @AFoletti ).

The layer selection translation comes from the chsdi code, translation source is public.transations. The current entries in bod_prod are correct. 
Since the table dataset and translations are linked with a trigger there are two possible reasons for the difference:

1. trigger does not work
1. translations table has been fixed manually without updating dataset table

**Comment by gjn** [comment] 2016-05-12 07:22
This is fixed.

**Comment by mariokeusen** [comment] 2016-10-06 13:53
I have found the same issue today again:
**UC I: s**earch for Grundwasser in the search field, choose the layer result "NAQUA-QUANT Messstellen" and load it to the map. 
**UC II:** open the bafu-topic -> waters -> state of groundwaters and add the same layer

**Result:** the layer has a different title in the selection than in the catalog and in the search result list. The title from the search and from the catalog is correct since it corresponds the current geocat-alternate title (the title from the selection is an previously used in geocat, but overwritten for quite a while now)
**Expected:** layer has the same title everywhere in map.geo.admin.ch

![layername_issue_selection](https://cloud.githubusercontent.com/assets/4577749/19154872/803aacf2-8bdc-11e6-8e89-fbe9574a6adb.PNG)

**Comment by gjn** [comment] 2016-10-06 14:03
I can't reproduce here. Caching issue? Did you try this in the morning? If yes, it might be fixed now because we had old layersConfig in cache.

**Comment by mariokeusen** [comment] 2016-10-07 06:59
Observed that by chance yesterday afternoon. But now I can't reproduce it anymore. Must have been something old in the cache...

**Comment by mariokeusen** [comment] 2016-10-27 04:27
I have again a difference: English app, load the new layer ch.bazl.spitallandeplaetze, compare catalog and selection:
Catalog: layername in EN. 
Selection: layername in FR

Expected: all the same language everywhere.
![lang_diff_selection_catalog](https://cloud.githubusercontent.com/assets/4577749/19754512/7b6705e4-9c0e-11e6-9dd5-66a93777488c.PNG)

**Comment by mariokeusen** [comment] 2016-10-27 04:39
Another issue for this particular layer that's seriously concerning me:
The layer title in the selection does not correspond to the layer title in the catalog even in FR language. In the catalog we have the correct title according to geocat.ch, in the selection not. Why that?

**Comment by loicgasser** [comment] 2016-10-27 07:32
This is only in english,

Translations in the layer tree come from geocat, and translations in catalog from your spreadsheet.

We probably didn't have them. A make translate should do the trick.

**Comment by loicgasser** [comment] 2016-10-27 07:36
And make translate it is.
https://github.com/geoadmin/mf-chsdi3/pull/2298

Should add that to the process. always update translations before deploy.

**Comment by mariokeusen** [comment] 2016-10-27 07:45
No, layer translations always come from geocat. only category translations for the layertree come from the spreadsheet.

**Comment by loicgasser** [comment] 2016-10-27 07:53
So, it's already in the guidelines, second step of deploying CHSDI.
https://github.com/geoadmin/doc-guidelines/blob/master/DEPLOY.md

And yes, it's possible, so let's put it this way, in the catalog they come directly from DB and in layertree they come from chsdi transaltions (po/mo).

**Comment by loicgasser** [comment] 2016-10-27 08:03
By the way those translations were added last minute on Tuesday.
bgdi_modified in translations
2016-10-25 14:32:28.527456

**Comment by loicgasser** [comment] 2016-10-27 08:08
So this is fixed at least in dev. I'll let @gjn decide whether we need an emergency deploy. (which requires a deploy of a new snapshot of chsdi and redeployment of the actual snapshot of geoadmin for caching reasons).

**Comment by gjn** [comment] 2016-10-27 08:49
This has been a repeated issue and we need to solve this once and for all.

The problem:
1) catalog gets layer translations from [view in bod](https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/models/bod.py#L390). it always delivers what's in bod
2) layersconfig gets layer translation from po files [via translate](https://github.com/geoadmin/mf-chsdi3/blob/master/chsdi/models/bod.py#L108), which only delivers what was translated by hand with make translate

IMO, we should remove the layer translations from the po translations files and get it 'live' from the bod for the layersConfig - unless we have other occurences where we get them from the po translations. Then we can say wie remove the translations from the catalog view and also use the po file approach.

@loicgasser Thoughts?

Please do an emergency deploy. I'll try to move this issue to mf-chsdi3.

**Comment by gjn** [comment] 2016-10-27 08:50
Can't move issues, so I keep it here even though fix is eiter in bod or in mf-chsdi3.

**Comment by loicgasser** [comment] 2016-10-27 09:04
Redeploying now.

Well, the main advantage of having those in the po, is performance related.
We avoid a bunch of requests to the bod with this solution. If you follow the guidelines, this should not happen. I think we have more that a couple of dependencies on that mechanism.

Rather than changing that, I would add the make translate CMD, to the deploydev script, thus making sure we don't forget to update those.

As a side note translations issues we had last time were coming from a bad deploy timing between chsdi and geoadmin, and not a missing translation. In general I think that our translation mechanism could be simpler as instead of adding translations manually to the empty.po file. We could simply "SELECT * FROM translations ORDER BY msg_id"

**Comment by gjn** [comment] 2016-10-27 09:13
Hmm. We have two sources for the same thing. This is a bad thing. I doubt performance plays a role here - views with so view entries are very fast. Anyhow, I understand that there might be other services requiring these resources in the *.po.

How about using the po translate mechanism for the catalog layer entries instead of getting those from the catalog view (and removing them from the view)?

Regarding make translate and po files:
We want to track the po files with git and creating snapshots based on git commits/tags. When we update translations during creation of the snapshot (in deploydev), then we don't have same state in git and snapshot. I'd rather have a check if translations are up-to-date before deploydev and abort it when it's not the case.

Also, agree, to have empty po file does not make sense.

**Comment by loicgasser** [comment] 2016-10-27 09:22
> We want to track the po files with git and creating snapshots based on git commits/tags. When we update translations during creation of the snapshot (in deploydev), then we don't have same state in git and snapshot. I'd rather have a check if translations are up-to-date before deploydev and abort it when it's not the case.

The idea is that you abort the deployment if some translations are missing.

**Comment by loicgasser** [comment] 2016-10-27 09:24
> How about using the po translate mechanism for the catalog layer entries instead of getting those from the catalog view (and removing them from the view)?

It would be consistent but still wrong...

**Comment by gjn** [comment] 2016-10-27 09:39
+1 and +1.

Still, no way to use translate for the catalog easy? (Instead of duplication info in the view?)

**Comment by loicgasser** [comment] 2016-10-27 09:44
Yes, we could do both. then it would make sense.

**Comment by loicgasser** [comment] 2016-10-27 09:52
Though as @mariokeusen rightly pointed it out. Categories translations come from spreadsheet.
If we are consistent with it, we should also put those in the translations.

So the proposal is as follow.

1. Abort deployment scripts if translations are not updated
2. Add categories in translation table. (via DB trigger most likely as it is the case in dataset)
3. Generate empty.po from DB.

Then it's a 2 step deploy process

4. Adapt views
5. Remove/adapt code in chsdi

OR

1. Abort deployment scripts if translations are not updated.

**Comment by loicgasser** [comment] 2016-10-27 10:08
translations and legends updated.
https://github.com/geoadmin/mf-chsdi3/releases/tag/r_161027

**Comment by gjn** [comment] 2016-10-27 11:06
Another proposal:

Can't we create the po files on the fly either in
1) when creating deploying snapshot
2) when creating snapshot
3) on post deploy hook
4) on application start

3 + 4 would assure that bod and po cache would always be in sync. No manual make translate anymore or check if it's done. This would mean we don't rack po files here anymore. I think that would be ok as we could track it with our bod_diff utility.

**Comment by loicgasser** [comment] 2016-10-27 11:28
I think tracking it is important.
When reviewing PR essentially for tooltips, extended and so on. We can control their quality. We often fix translations thanks to the PR in CHSDI.

**Comment by loicgasser** [comment] 2016-10-27 11:29
Bod don't show all translations and only shows fields and layers that are different in geocat and bod

**Comment by gjn** [comment] 2016-10-27 11:39
With bod_diff, I meant this: https://github.com/geoadmin/db/compare/tag_bod_master20160713...tag_bod_master20160803
We could extend this easily to include the translations, no?

And what about our bod review process with started? Do we stop it? Start from scratch? Start using it?

**Comment by loicgasser** [comment] 2016-10-27 13:14
The BOD process is ready. I can't do that alone, need to work with @ltclm, document and form people.

**Comment by procrastinatio** [comment] 2016-10-27 15:18
Do we really need `gettext`? I mean, we only use the simpliest feature of it (no plurals, placeholder replacement, languages having many plurals form, etc.)

**Comment by gjn** [comment] 2016-10-30 20:09
Alternatives?

**Comment by gjn** [comment] 2016-11-08 12:50
The deploy process has been adapted to check for pending translations.

**Closed** 2016-11-08 12:52 UTC
Labels: 1st prio, bug
