### ISSUE TITLE
[Improvement] Object information available for external WMS on import

### ISSUE THREAD

**Issue by nliaudat** [geoadmin/mf-geoadmin3#2296] opened 2015-04-16 15:04 UTC
Hi, 

It could be great to implement "Object information" tool available for external WMS (imported).
External wms server have getfeatureinfo capabilites. 

Linked to https://github.com/geoadmin/mf-geoadmin3/issues/1567 to implement the identify request per layer.

Regards
Nicolas Liaudat

**Comment by davidoesch** [comment] 2015-04-17 13:42
duplicate of https://github.com/geoadmin/mf-geoadmin3/issues/1148

**Closed by davidoesch** 2015-04-17 13:42 UTC
