### ISSUE TITLE
[Feedback-Tool] - "Send" button disappears after moving the window.

### ISSUE THREAD

**Issue by p1d1d1** [geoadmin/mf-geoadmin3#2795] opened 2015-10-26 12:57 UTC
To reproduce:

* Open the "Feedback Tool"
* Drag the window --> Send button no more available

Tested on IE, Firefox, Chrome

**Comment by davidoesch** [comment] 2015-10-26 13:02
duplicate of  https://github.com/geoadmin/mf-geoadmin3/issues/2770

**Closed by davidoesch** 2015-10-26 13:02 UTC
Labels: bug
