### ISSUE TITLE
3D: Site marker not shown

### ISSUE THREAD

**Issue by nadine-piveteau** [geoadmin/mf-geoadmin3#4002] opened 2017-10-23 14:48 UTC
The red site marke does not appear when you look for a place.

Tested on Chrome, Firefox, Edge, IE11

Reproduce: 
1. Open [link ](https://mf-chsdi3.int.bgdi.ch/shorten/7665529faf)
2. Enter in swisssearch `Thun(BE)` (or any other place)

Results: Marker does not appear

**Comment by oterral** [comment] 2017-10-27 14:28
duplicate of #3354

**Closed by oterral** 2017-10-27 14:28 UTC
Labels: 3D, 3rd prio, bug

**Comment by loicgasser** [comment] 2017-11-01 16:02
Problem is with the artificially introduced `()` in the label.
we could stript those characters in the search and it would do the trick.
