### ISSUE TITLE
search  results can not be closed

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3359] opened 2016-06-02 15:58 UTC
open

https://map.geo.admin.ch/?X=262019.55&Y=636182.13&zoom=7&lang=de&topic=ech&bgLayer=ch.swisstopo.pixelkarte-grau&layers=ch.swisstopo.zeitreihen,ch.astra.ivs-gelaendekarte,ch.swisstopo.swissboundaries3d-gemeinde-flaeche.fill,ch.astra.ivs-reg_loc,ch.astra.ivs-nat-verlaeufe,ch.astra.ivs-nat,ch.swisstopo.swisstlm3d-wanderwege&layers_visibility=false,true,true,true,true,true,false&layers_timestamp=18641231,,,,,,&catalogNodes=457,687,510,702&layers_opacity=1,0.75,1,1,1,1,1

enter bern

close results via X

this stays
![unbenannt3](https://cloud.githubusercontent.com/assets/4577727/15751744/7a1b21ac-28eb-11e6-9e52-82fc8cd5e87d.PNG)

expected result

it dissapears

seems to be a side effect of :limit imho

**Comment by gjn** [comment] 2016-06-02 17:21
Duplicate of https://github.com/geoadmin/mf-geoadmin3/issues/3350, which is already solved in master.

**Closed by gjn** 2016-06-02 17:21 UTC
Labels: 2nd prio, bug
