### ISSUE TITLE
äbnit (BE) search result not always the same 

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2062] opened 2015-01-08 16:31 UTC
search "äbnit" 

in the result you find a Äbnit (BE) - Vechigen

select it zoom to it

then search "Äbnit (BE)"

select it from the result 

Result: it is another location

question: when there are 2 entries same commune: why does it not show both initially and why does it not show the same in the ranking?

**Comment by loicgasser** [comment] 2015-01-08 16:59
The enter takes the selected entry in the list (highlighted entry). So not a bug.

**Comment by cedricmoullet** [comment] 2015-01-08 17:11
I have also not the feeling that it's a bug

**Comment by davidoesch** [comment] 2015-01-08 17:18
ok I looket with it at loic- he confimred it is  strange

furthermore
"Äbnit (BE) - Vechig" I expect to find to time
Äbnit (BE) - Vechigen
Äbnit (BE) - Vechigen

**Comment by gjn** [comment] 2015-02-26 10:18
There were 2 results for Äbnit Vechigen. Typeahead simply removed one results because it had the exact same entry: so this is a bug imo. With the new angular based search (on next deploy), the user will always get 2 "Äbnit (BE) - Vechig" results in the list.

Now why we have 2 results with same label is something coming from the data side. Maybe @ltclm knows why (heres the request: http://mf-chsdi3.int.bgdi.ch/rest/services/ech/SearchServer?type=locations&searchText=%C3%A4bnit%20(BE)&lang=de, both duplicated results come from sn25, same weigth, but different coordinates and ids. I doubt we can do anything about this.

On the other hand, looking for "Äbnit (BE) - Vechig" does indeed not return this location, which should be the case. @ponceta Can you take this use case into our search reference list? Then we can close this issue.

**Comment by loicgasser** [comment] 2015-02-26 11:03
The search field for this entry is:
`detail: "aebnit be"`

while the label is:
`label: "<b>Äbnit</b> (BE) - Rüschegg"`

so BE is actually not present in the search field. (as well as `-`)
We should maybe try to format our search field the same way we format our labels. (minus the balise of course)

**Comment by davidoesch** [comment] 2015-02-26 12:25
same for Bettenhausen BE  gives to results

**Comment by ltclm** [comment] 2015-02-27 08:02
The two results for ``Äbnit Vechigen`` come from the data:

```sql
select * FROM tlm.swissnames_sn25_und_tlm  where lower(name) like '%äbnit%' and lower(gemname) like '%vechig%'
 objectid | objectorig | objectval | yearofchan | name  | gemnr | gemname  | kanton | altitude |                      the_geom                      | bgdi_source | bgdi_modified |       bgdi_created        | bgdi_modified_by | bgdi_created_by | bgdi_id
----------+------------+-----------+------------+-------+-------+----------+--------+----------+----------------------------------------------------+-------------+---------------+---------------------------+------------------+-----------------+---------
    44472 | LK25       | Flurname  |       2000 | Äbnit |   359 | Vechigen | BE     |        0 | 0101000020155500009A999999C79722419A999999ED7C0841 | sn25        |               | 2014-05-15 07:26:46.74367 |                  | pgkogis         |   44472
    44473 | LK25       | Flurname  |       2005 | Äbnit |   359 | Vechigen | BE     |        0 | 010100002015550000CDCCCCCCCAA0224100000000CCDF0841 | sn25        |               | 2014-05-15 07:26:46.74367 |                  | pgkogis         |   44473
(2 rows)

```
Apparently sn25 has two releases for äbnit Vechigen (2000 and 2005) for whatever reason.

@davidoesch ``bettenhausen be`` returns two results, one from gg25 and one from sn25:
http://api3.geo.admin.ch/rest/services/ech/SearchServer?type=locations&searchText=bettenhausen%20be&lang=de
```bash
{
id: 529,
weight: 15,
attrs: {
origin: "gg25",
geom_quadindex: "02112",
layerBodId: "ch.swisstopo.swissboundaries3d-gemeinde-flaeche.fill",
featureId: "973",
lon: 7.708376407623291,
detail: "bettenhausen be",
rank: 2,
geom_st_box2d: "BOX(619202.103750002 223037.337499999,621753.798749998 225753.127500001)",
lat: 47.170204162597656,
num: 1,
y: 620450.9375,
x: 224395.234375,
label: "<b>Bettenhausen (BE)</b>"
}
},
{
id: 31843,
weight: 15,
attrs: {
origin: "sn25",
geom_quadindex: "021123011003012301321",
lon: 7.714827537536621,
detail: "bettenhausen be",
rank: 5,
geom_st_box2d: "BOX(620938.9 224718.8,620938.9 224718.8)",
lat: 47.173099517822266,
num: 1,
y: 620938.875,
x: 224718.796875,
label: "<b>Bettenhausen</b> (BE) - Bettenhausen"
}
},
```

**Comment by davidoesch** [comment] 2015-02-27 09:15
@mariokeusen with the Import of swissnames3d we have to remove Duplikates of sn25 and gg25 . Otherwise we will have a big mess Can You Organize a brainstorming with clm?

**Comment by gjn** [comment] 2015-02-27 09:22
We have this duplication without swissnames3d already...

But swissnames3d will add to the problematic. See current state on dev, where swissnames3D are included (and marked as swissnames3d)

e.g. http://mf-geoadmin3.dev.bgdi.ch/?swisssearch=trimmis

I agree that we need to brainstorm on how we want to merge this data to be the most useful.

**Comment by mariokeusen** [comment] 2015-02-27 09:25
Ok, who to be invited? clm, jeg, kem, oed?

**Comment by davidoesch** [comment] 2015-02-27 09:31
The issue is: swisstopo has Different products and each of them contains gazetteer info (sn25 swiss names 3d, swiss boundaries) and they want to have all found by default,  then there are legacy datasets (gg25) which are needed since they new products do not contain some info ( sac huts) to be reviewed. 

Goal: in the swisssearch we have the min common delimiter. Result are also linked with the right zoomlevel ( you see on the map what u searched for) Product specific names  are  found if product is active- attribute search.

A year ago I warned topo regarding the mess --- hello samichlaus

**Comment by gjn** [comment] 2015-02-27 09:46
For map.geo.admin.ch, we have to be user centric.

For other services (which can be part of api3.geo.admin.ch), we can be prodcut centric.

**Comment by mariokeusen** [comment] 2015-02-27 10:08
For the map viewer we could do the following:
Search: we only import what is useful from swissnames3D from a search user's point of view. Goal: unique search results.
Data layer / bg layer: integrate the full swissnames 3d information (the "product") with the visualization planned for June. To define with Topo, if it will need a (searchable) data layer or if it's enough to put the swissnames labels onto the "luftbild" bg layer

**Comment by davidoesch** [comment] 2015-02-27 10:08
+1

On Fri, Feb 27, 2015 at 10:46 AM, Gilbert Jeiziner <notifications@github.com

**Comment by ltclm** [comment] 2015-02-27 10:27
@davidoesch  maybe im wrong but i think swissnames3d will completely replace sn25.

**Comment by davidoesch** [comment] 2015-02-27 10:36
@ltclm i do hope so as well since http://mf-geoadmin3.dev.bgdi.ch/?swisssearch=Bächlitalhütte  gives a result... but you never know. and it is hard to calculate a diff between gg25 sn25 and swissnames3d sind the zoom factor is missing

**Comment by ponceta** [comment] 2015-04-27 13:21
Referenced on #2170
Reopen when news come up

**Closed by ponceta** 2015-04-27 13:21 UTC
Labels: 3rd prio
