### ISSUE TITLE
link to wms in infobox concatenates different wms

### ISSUE THREAD

**Issue by rfrancel** [geoadmin/mf-geoadmin3#3218] opened 2016-03-16 14:15 UTC
When you click on the link to wms in the infobox of a layer, you should be redirected to the getcap of the associated wms. It seems that when a layer is associated to more than one wms, the link concatenates them, giving a wrong url.
For example:
https://map.geo.admin.ch/?X=190000.00&Y=660000.00&zoom=1&topic=ech&lang=fr&bgLayer=ch.swisstopo.pixelkarte-farbe&layers=ch.bafu.moose
And here the resulting  ‘link to wms’:
https://wms.geo.admin.ch/?REQUEST=GetCapabilities&SERVICE=WMS&VERSION=1.0.0%20|%20http://wms-swisstopowms.prod.bgdi.ch

**Comment by oterral** [comment] 2016-04-12 09:03
@rfrancel  may be it's more a CHSDI issue if the problem is in the info box:

https://api3.geo.admin.ch/rest/services/all/MapServer/ch.bafu.moose/legend?lang=fr

**Comment by oterral** [comment] 2016-07-21 06:29
Fixed on prod

**Closed by oterral** 2016-07-21 06:29 UTC
Labels: 3rd prio
