### ISSUE TITLE
Time enables lubis images do load / only slow

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3739] opened 2017-03-16 14:28 UTC
open
https://map.geo.admin.ch/?topic=luftbilder&lang=de&bgLayer=ch.swisstopo.pixelkarte-grau&layers=ch.swisstopo.lubis-luftbilder_schwarzweiss,ch.swisstopo.lubis-luftbilder_farbe&layers_timestamp=19491231,&catalogNodes=1179,1180,1186&X=240675.19&Y=702128.63&zoom=6&time=1949
try to use the time slider,
Result:
images not shown
![att00001](https://cloud.githubusercontent.com/assets/4577727/24000939/02259624-0a5d-11e7-9dad-50d254f79790.jpg)

or as in here
[Screencast_2017-03-16-15-25-01.zip](https://github.com/geoadmin/mf-geoadmin3/files/847961/Screencast_2017-03-16-15-25-01.zip)

-> time bug? since last update of lubis  
Customer feedback ID : 2017031614271656

**Comment by gjn** [comment] 2017-03-16 15:23
I can't reproduce this exact behaviour, but I can reproduce strange behaviours with these layers.

Here's what you can try to reproduce:

1. [Open This link](https://map.geo.admin.ch/?topic=luftbilder&lang=de&bgLayer=ch.swisstopo.pixelkarte-grau&layers=ch.swisstopo.lubis-luftbilder_schwarzweiss,ch.swisstopo.lubis-luftbilder_farbe&layers_timestamp=19761231,&catalogNodes=1179,1180,1186&X=251723.99&Y=677558.36&zoom=4&time=1976). You should see red points around Zurich

2. Zoom into Zurich city until you see not red points but squares with 76 in them. zoom should be 8. So pretty far in until you see this: 
![image](https://cloud.githubusercontent.com/assets/2572317/24003701/7a11cba6-0a64-11e7-91ed-6e69a2da66cf.png)

3. Now move the timeslider to 1977 or 1978. What you'll see is still 1976 points, but client zoomed from higher levels up. Depending on zoomlevel, you can also see only red points that are client zoomed.

@oterral Can you have a look?
@ltclm Can we exclude that it's a cache issue (cache not invalidated, or invalidated too early?) after last weeks issues?

**Comment by ltclm** [comment] 2017-03-16 15:33
this layer was not affected by the issues we had last week, and these tiles are new, so it's probably not a cache flush issue.
If you zoom out and in again in 1977 or 1978, the red points are disappearing.

**Comment by oterral** [comment] 2017-03-20 07:50
Yes, it seems it's ol display interim tiles of the previous timestamp because it has 204 tiles for theis year.

**Comment by oterral** [comment] 2017-03-20 07:53
Should be fixed by https://github.com/geoadmin/mf-geoadmin3/pull/3662.
https://mf-geoadmin3.int.bgdi.ch/teo_204tiles/index.html?lang=fr&topic=luftbilder&bgLayer=ch.swisstopo.pixelkarte-grau&X=248140.97&Y=683043.97&dev3d=true&zoom=11&debug&layers=ch.swisstopo.lubis-luftbilder_schwarzweiss,ch.swisstopo.lubis-luftbilder_farbe&layers_timestamp=19761231,19811231&layers_visibility=true,false&time=1976

**Comment by davidoesch** [comment] 2017-03-20 07:58
Uh now I get for your testlink this: red areas all over
![image](https://cloud.githubusercontent.com/assets/4577727/24091913/69d7fdc0-0d4b-11e7-9e5c-03f1fba915f1.png)

**Comment by oterral** [comment] 2017-03-20 08:03
red area represents 204 tiles.

**Comment by gjn** [comment] 2017-04-12 11:40
Probably fix(able) with https://github.com/geoadmin/mf-geoadmin3/pull/3662

**Comment by oterral** [comment] 2017-06-12 12:00
Fixed with https://github.com/geoadmin/mf-geoadmin3/pull/3829

**Closed by oterral** 2017-06-12 12:00 UTC
Labels: 1st prio, bug, question
