### ISSUE TITLE
Map doesn't display after a search

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#3711] opened 2017-02-06 08:29 UTC
1. Start map.geo.admin.ch
2. Search for "Bergerie 38 Payerne"

-> Map doesn't appear

**Comment by loicgasser** [comment] 2017-02-06 08:34
Data update issue, @ltclm working on it right.

**Comment by loicgasser** [comment] 2017-02-06 08:43
duplicate of https://github.com/geoadmin/mf-geoadmin3/issues/3709

**Closed by loicgasser** 2017-02-06 08:43 UTC
Labels: 1st prio

**Comment by davidoesch** [comment] 2017-02-06 09:50
done
