### ISSUE TITLE
Tooltip on mobile for KML doesn't work

### ISSUE THREAD

**Issue by cedricmoullet** [geoadmin/mf-geoadmin3#3214] opened 2016-03-16 07:25 UTC
https://map.geo.admin.ch/?lang=fr&topic=ech&bgLayer=ch.swisstopo.pixelkarte-grau&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,KML%7C%7Chttp:%2F%2Fwww.rsr-prod.ch%2Fcartes%2Fbva%2FTransmission%2520des%2520donnees%2520au%2520BVA%2520par%2520les%2520communes.kml&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&X=159464.45&Y=539948.82&zoom=3

**Comment by cedricmoullet** [comment] 2016-03-16 07:32
Pages crashes on iPhone 6 but works well on iPad Pro...

**Comment by loicgasser** [comment] 2016-03-16 07:56
Works well on Android. (Sony)

**Comment by gjn** [comment] 2016-03-16 09:50
Works well on my Jolla - even though a little slow.

**Comment by davidoesch** [comment] 2016-03-16 17:22
Works not on Android 601 Nexus p...

**Comment by oterral** [comment] 2016-04-12 09:09
tooltip works with difficulty on low zoom level but well on high zoom level.

**Comment by oterral** [comment] 2016-05-10 11:35
It seems related to https://github.com/openlayers/ol3/pull/5078

Problem happens on high zoom level. Since the pointer down event triggers a map render, if there is a lot of vectors data displayed, the rendering of the map takes too long so the time difference between touch start event and touch end event https://github.com/geoadmin/mf-geoadmin3/blob/master/src/components/map/MapService.js#L304 is greater than 300 ms

**Comment by gjn** [comment] 2016-09-06 12:00
Maybe update ol3 fixes this. @oterral will verify.

**Comment by loicgasser** [comment] 2016-09-27 11:50
To verify with ol3 update.

**Comment by oterral** [comment] 2017-01-06 14:04
The bug is fixed in ol3 . Since the link is no more valid we can't test to be sure it's fixed. Feel free to re-open it if you can reproduce.

**Closed by oterral** 2017-01-06 14:04 UTC
Labels: 1st prio
