### ISSUE TITLE
[Geolocation] Button rotation according to map rotation don't work

### ISSUE THREAD

**Issue by pfanguin** [geoadmin/mf-geoadmin3#3348] opened 2016-06-01 13:50 UTC

**Comment by gjn** [comment] 2016-06-02 07:59
@rfrancel We think this was ontroduced via your orientation fix you did. Could you verify?

**Comment by rfrancel** [comment] 2016-06-17 13:37
@oterral  I reassign this to you. From what I have investigated,the bug is present with or without the changes I've made. This bug cannot be reproduced on our android (Android 4.2.1, chrome 50) device, but it was found on Android 5.1.1 with chrome 45 (Pauline's phone). Good luck!

**Comment by oterral** [comment] 2016-07-15 13:51
Can't reproduce. Works on my android 5 and chrome 51

**Comment by gjn** [comment] 2016-08-02 11:18
We close.

**Closed by gjn** 2016-08-02 11:18 UTC
Labels: 2nd prio
